name: Dev CLI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        include:
          # Windows
          - build: windows_amd64
            name: windows_amd64
            os: ubuntu-latest
            goos: windows
            goarch: amd64
            file: wh.exe

          # Linux
          - build: linux-amd64
            name: linux_amd64
            os: ubuntu-latest
            goos: linux
            goarch: amd64
            file: wh

          - build: darwin-arm64
            name: darwin_arm64
            os: ubuntu-latest
            goos: darwin
            goarch: arm64
            file: wh

          # Mac
          - build: darwin-amd64
            name: darwin_amd64
            os: ubuntu-latest
            goos: darwin
            goarch: amd64
            file: wh
        
    steps:
    - name: Prepare - Checkout
      uses: actions/checkout@v4.0.0

    - name: Prepare - Inject short Variables
      uses: rlespinasse/github-slug-action@v4.3.2

    - name: Prepare - Set up Zip
      uses: montudor/action-zip@v1.0.0

    - name: Prepare - Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
        cache-dependency-path: client/go.sum

    - name: Prepare - Display Go version
      run: go version

    - name: Build - Install dependencies
      run: go get .
      working-directory: ./client

    - name: Build
      run: go build -o dist/${{ matrix.name }}/${{ matrix.file }} main.go
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      working-directory: ./client

    - name: Publish Archive
      run: mkdir archives && ls -R && cd dist/${{ matrix.name }} && zip -r ../../archives/${{ matrix.name }}.zip *
      working-directory: ./client
        
    - name: Publish - Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: client/archives/${{ matrix.name }}